ACCURACY:
  'k_per_decade_for_bao': 50
  'k_per_decade_for_pk': 50
COSMO_SETTINGS:
  'P_k_max_1/Mpc': 50
  'output' : 'mPk'
  'non linear' : 'halofit'
  'z_max_pk' : 5.0
  'N_ncdm': 1
  'T_cmb' : 2.7255
  'nonlinear_min_k_max' : 100.
  'k_pivot' : 0.05
LCDM :
  'Omega_k' : 0
  'YHe' : 0.2454006
w0waCDM :
  'Omega_Lambda' : 0.0
  'Omega_k' : 0
  'YHe' : 0.2454006